/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lithan.liferay.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lithan.liferay.service.model.Servic;
import com.lithan.liferay.service.service.ServicLocalServiceUtil;

/**
 * The extended model base implementation for the Servic service. Represents a row in the &quot;AAA_Servic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServicImpl}.
 * </p>
 *
 * @author joymen
 * @see ServicImpl
 * @see com.lithan.liferay.service.model.Servic
 * @generated
 */
public abstract class ServicBaseImpl extends ServicModelImpl implements Servic {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a servic model instance should use the {@link Servic} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ServicLocalServiceUtil.addServic(this);
		}
		else {
			ServicLocalServiceUtil.updateServic(this);
		}
	}
}